services:
  flask:
    build: "./python"
    volumes:
      - "./python:/app"
    ports:
      - "5555:5555"
    command: "pipenv run flask run --host 0.0.0.0 --port 5555"
    environment:
      - FLASK_APP=main